# Generated by Django 5.0.6 on 2024-05-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=254)),
                ('Standard', models.CharField(max_length=100)),
                ('Math', models.IntegerField()),
                ('Hindi', models.IntegerField()),
                ('English', models.IntegerField()),
                ('Social', models.IntegerField()),
                ('Science', models.IntegerField()),
                ('Sanskrit', models.IntegerField()),
            ],
        ),
    ]
